version: '3'

services:
  app:
    image: 'movierama:latest'
    build:
      context: .
    container_name: movierama
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgresqldb:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    container_name: postgresqldb
    environment:
      - POSTGRES_DB=movierama
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres